# Generated by Django 5.1.1 on 2024-10-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='fotos/categorias_apoio/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qualificacao', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(upload_to='fotos/equipe/')),
                ('biografia', models.TextField(max_length=300, verbose_name='breve biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=100, verbose_name='descrição')),
                ('imagem', models.ImageField(upload_to='fotos/ferramentas/')),
                ('url', models.URLField(default='#', help_text='http://www.exemplo.com/ferramenta-site', verbose_name='link de direcionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('thumbnail', models.ImageField(upload_to='artigos/thumbnails/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.equipe')),
            ],
        ),
    ]
