# Generated by Django 5.1.1 on 2024-10-12 23:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{0,3}\\s?\\(?\\d{0,2}\\)?\\s?[\\d\\-\\s]{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.ImageField(upload_to='icones/redes_sociais/')),
                ('url', models.URLField()),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.contato')),
            ],
        ),
    ]
