# Generated by Django 5.1.1 on 2024-10-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_textosecao_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='mainsite.categoriavideo', to_field='nome'),
        ),
    ]
