# Generated by Django 5.1.1 on 2024-10-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_video_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textosecao',
            name='texto_botao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='textosecao',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
