# Generated by Django 5.1.1 on 2024-10-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_textosecao_texto_botao_alter_textosecao_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='biografia',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='breve biografia'),
        ),
        migrations.AlterField(
            model_name='textosecao',
            name='subtitulo',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
