# Generated by Django 5.1.1 on 2024-10-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_contato_cidade_alter_equipe_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='subcategoriaapoio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas', to='mainsite.categoriaapoio'),
        ),
    ]
