# Generated by Django 5.1.1 on 2024-10-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicoforum',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='ComentarioTopico',
        ),
        migrations.DeleteModel(
            name='TopicoForum',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
